stages:
  - test
  - build
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/backend/.gradle

frontend-lint-test:
  stage: test
  image: node
  script:
    - cd frontend
    - npm install --progress=false
    - npm run lint
  interruptible: true

backend-gradle-test:
  stage: test
  image: gradle:6.7.1-jdk11
  script:
    - cd backend
    - gradle check
  interruptible: true

frontend-build:
  stage: build
  image: node
  script:
    - cd frontend
    - npm install --progress=false
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE != "$CI_DEFAULT_BRANCH"'
      when: manual
    - if: $CI_MERGE_REQUEST_ID
    when: never
   - if: '$CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"'
  artifacts:
    expire_in: 1 day
    paths:
      - frontend/dist
  interruptible: true

backend-build:
  stage: build
  image: gradle:6.7.1-jdk11
  script:
    - cd backend
    - gradle assemble
  rules:
    - if: '$CI_PIPELINE_SOURCE != "$CI_DEFAULT_BRANCH"'
      when: manual
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"'
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: 1 day
  interruptible: true

deploy-frontend:
  image: debian
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y git curl
    - git config user.name "CI durch Paul Glaß"
    - subtree_hash=$(git subtree split --prefix frontend HEAD --)
    - echo "Deploy frontend from subtree hash $subtree_hash"
    - git push "https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_FRONTEND.git" "${subtree_hash}:master" --force
  rules:
    - if: '$CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"'
      when: manual

deploy-backend:
  image: debian
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y git curl
    - git config user.name "CI durch Paul Glaß"
    - subtree_hash=$(git subtree split --prefix backend HEAD --)
    - echo "Deploy backend from subtree hash $subtree_hash"
    - git push "https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_BACKEND.git" "${subtree_hash}:master" --force
  rules:
    - if: '$CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"'
      when: manual
