stages:
  - test
  - build
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/backend/.gradle

frontend-lint-test:
  stage: test
  image: node
  script:
    - cd frontend
    - npm install --progress=false
    - npm run lint

backend-gradle-test:
  stage: test
  image: gradle:6.7.1-jdk11
  script:
    - cd backend
    - gradle check

frontend-build:
  stage: build
  image: node
  script:
    - cd frontend
    - npm install --progress=false
    - npm run build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  artifacts:
    expire_in: 1 day
    paths:
      - frontend/dist
  needs:
    - "frontend-lint-test"
    - "backend-gradle-test"

backend-build:
  stage: build
  image: gradle:6.7.1-jdk11
  script:
    - cd backend
    - gradle assemble
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: 1 day
  needs:
    - "frontend-lint-test"
    - "backend-gradle-test"

deploy-frontend:
  image: debian
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y git curl
    - git config user.name "CI durch Paul Glaß"
    - subtree_hash=$(git subtree split --prefix frontend HEAD --)
    - echo "Deploy frontend from subtree hash $subtree_hash"
    - git push "https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_FRONTEND.git" "${subtree_hash}:master" --force
  when: manual
  needs:
    - "frontend-build"
  only:
    variables:
      - ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $GITLAB_USER_ID == "1543")

deploy-backend:
  image: debian
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y git curl
    - git config user.name "CI durch Paul Glaß"
    - subtree_hash=$(git subtree split --prefix backend HEAD --)
    - echo "Deploy backend from subtree hash $subtree_hash"
    - git push "https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_BACKEND.git" "${subtree_hash}:master" --force
  when: manual
  needs:
    - "backend-build"
  only:
    variables:
      - ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $GITLAB_USER_ID == "1543")
